---
sidebar: sidebar 
permalink: reference-supported-configs.html 
keywords: ec2, instance, type, vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations 
summary: Cloud Volumes ONTAP est disponible dans plusieurs configurations dans AWS et Azure. 
---
= Configurations compatibles
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP est disponible dans AWS et Azure avec deux options de tarification : le paiement à l'utilisation ou le modèle BYOL (où vous apportez votre propre licence). Le paiement basé sur l'utilisation vous permet de choisir parmi trois configurations : explore, Standard ou Premium.



== Cloud Volumes ONTAP pour AWS

Dans AWS, vous pouvez déployer Cloud Volumes ONTAP en tant que système unique ou paire HA.

[cols="h,d,d,d,d"]
|===
|  | Découvrir | Standard | Premium | BYOL 


| Types d'instances EC2 | m4.xlarge  a| 
* m4.2xlarge
* r4.xlarge

 a| 
* c4.4xlarge
* c4.8xlarge
* m4,4xlarge
* r4.2xlarge

 a| 
* c4.4xlarge
* c4.8xlarge
* m4.xlarge
* m4.2xlarge
* m4,4xlarge
* r4.xlarge
* r4.2xlarge




| Stockage sous-jacent 4+| SSD à usage générique, SSD IOPS provisionnés, HDD optimisés pour le débit et HDD jusqu'à 16 Tio par disque 


| Capacité système maximale (disques + stockage objet) | 2 To | 10 To | 368 To | 368 Tio par licence 
|===
Remarques :

. Si vous activez la hiérarchisation des données, la limite de capacité d'un système reste la même. La limite de capacité inclut à la fois les disques et le stockage objet.
. Le Tiering des données est pris en charge avec Cloud Volumes ONTAP Standard, Premium et BYOL.
. Lorsque vous choisissez un type d'instance EC2, vous pouvez indiquer s'il s'agit d'une instance partagée ou dédiée.
. Les performances d'écriture améliorées sont prises en charge lorsque les SSD EBS sont utilisés avec Cloud Volumes ONTAP Standard, Premium et BYOL.
. Pour la prise en charge de chaque région AWS, consultez la section https://cloud.netapp.com/cloud-volumes-global-regions["Régions Cloud volumes Global"^].




== Cloud Volumes ONTAP pour Azure

Dans Azure, vous pouvez déployer Cloud Volumes ONTAP en tant que système à un seul nœud.

[cols="h,d,d,d,d"]
|===
|  | Découvrir | Standard | Premium | BYOL 


| Types de machines virtuelles | DS3_v2  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2

 a| 
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2




| Stockage sous-jacent 4+| Disques gérés HDD standard, disques gérés SSD standard et disques gérés SSD premium, jusqu'à 32 To par disque 


| Capacité système maximale (disques + stockage objet) | 2 To | 10 To | 368 To | 368 Tio par licence 
|===
Remarques :

. Si vous activez la hiérarchisation des données, la limite de capacité d'un système reste la même. La limite de capacité inclut à la fois les disques et le stockage objet.
. Le Tiering des données n'est pas pris en charge avec le type de machine virtuelle DS3_v2.
. Les performances améliorées en écriture sont activées lorsque vous utilisez des disques de stockage Azure Premium, mais pas avec le type de machine virtuelle DS3_v2.
. Pour la prise en charge par région Azure, consultez la section https://cloud.netapp.com/cloud-volumes-global-regions["Régions Cloud volumes Global"^].

